version: "3"
services:
  nusa-postgres:
    container_name: nusaDatabase
    image: postgres:15.4-bookworm
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5451:5432
    restart: always
